---
  auth_id:
    description: "Plivo Auth ID"
    type: "string"
    secret: false
    required: true
  auth_token:
    description: "Plivo Auth Token"
    type: "string"
    secret: true
    required: true
